name: NPM Publish Package

on:
  workflow_call:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  quality:
    name: Quality Control
    uses: ./workflows/nodejs_quality_control.yml
    secrets: inherit

  publish:
    name: Publish NPM
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Publish Package to NPM
        env:
          HUSKY: 0
        run: |
          npm i -g pnpm @semantic-release/changelog @semantic-release/git semantic-release
          pnpm i --frozen-lockfile --ignore-scripts
          pnpm build
          semantic-release
