name: GCP Cloud Run Deploy

on:
  workflow_call:
    inputs:
      ingress:
        type: string
        default: all
      execution-environment:
        type: string
        default: gen2
      port:
        type: number
        default: 8080
      cpu:
        type: number
        default: 1
      memory:
        type: string
        default: 512Mi
      min-instances:
        type: number
        default: 0
      max-instances:
        type: number
        default: 10
      concurrency:
        type: number
        default: 100
      timeout:
        type: number
        default: 150
      deploy-args:
        type: string

env:
  GCP_PREFIX: ${{ fromJSON('{"master":"prd","stage":"stg"}')[github.ref_name] }}
  CLOUD_RUN_IMAGE: ${{ format('gcr.io/{0}-cnpja/{1}-{2}:{3}', fromJSON('{"master":"prd","stage":"stg"}')[github.ref_name], fromJSON('{"master":"prd","stage":"stg"}')[github.ref_name], github.event.repository.name, github.sha) }}

jobs:
  deploy:
    name: Cloud Run Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate Google Cloud Platform
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets[format('{0}_GCP_SERVICE_ACCOUNT_KEY', fromJSON('{"master":"PRD","stage":"STG"}')[github.ref_name])] }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        install_components: beta

    - name: Configure Google Cloud CLI
      run: gcloud auth configure-docker

    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      continue-on-error: true
      with:
        name: build-artifacts

    - name: Build Container Image
      run: |
        docker build . -t $CLOUD_RUN_IMAGE \
          --build-arg NPM_TOKEN=${{ secrets.GLB_NPM_TOKEN }} \

    - name: Publish Image to Container Registry
      run: docker push $CLOUD_RUN_IMAGE

    - name: Deploy Image on Cloud Run
      run: |
        gcloud beta run deploy $GCP_PREFIX-${{ github.event.repository.name }} \
          --project $GCP_PROJECT \
          --platform=gke \
          --cluster=$GCP_PREFIX-gke \
          --cluster-location=us-east1-d \
          --image $CLOUD_RUN_IMAGE \
          --ingress ${{ inputs.ingress }} \
          --port ${{ inputs.port }} \
          --cpu ${{ inputs.cpu }} \
          --memory ${{ inputs.memory }} \
          --max-instances ${{ inputs.max-instances }} \
          --min-instances ${{ inputs.min-instances }} \
          --concurrency ${{ inputs.concurrency }} \
          --timeout ${{ inputs.timeout }} \
          ${{ inputs.deploy-args }} \
