name: Node.js Cloud Run Deploy

on:
  workflow_call:
    inputs:
      ingress:
        type: string
      execution-environment:
        type: string
      cpu:
        type: number
      memory:
        type: string
      max-instances:
        type: number
      concurrency:
        type: number
      timeout:
        type: number
      args:
        type: string

jobs:
  quality:
    name: Quality Control
    uses: ./.github/workflows/nodejs_quality_control.yaml
    secrets: inherit

  configuration:
    name: Environment Configuration
    runs-on: ubuntu-latest
    needs: quality

    steps:
    - name: Configure Environment
      if: endsWith(github.ref, '/stage')
      run: echo "NODE_ENV=staging" >> $GITHUB_ENV

    - name: Configure Environment
      if: endsWith(github.ref, '/master')
      run: echo "NODE_ENV=production" >> $GITHUB_ENV

  deploy:
    name: Cloud Run Deploy
    uses: ./.github/workflows/gpc_cloud_run_deploy.yaml
    secrets: inherit
    needs: configuration

    with:
      ingress: ${{ inputs.ingress }}
      execution-environment: ${{ inputs.execution-environment }}
      cpu: ${{ inputs.cpu }}
      max-instances: ${{ inputs.max-instances }}
      concurrency: ${{ inputs.concurrency }}
      timeout: ${{ inputs.timeout }}
      args: |
        --set-env-vars="NODE_ENV=$NODE_ENV" \
        ${{ inputs.args }}
