name: Node.js Cloud Run Deploy

on:
  workflow_call:
    inputs:
      ingress:
        type: string
        default: all
      execution-environment:
        type: string
        default: gen2
      cpu:
        type: number
        default: 1
      memory:
        type: string
        default: 512Mi
      max-instances:
        type: number
        default: 10
      concurrency:
        type: number
        default: 100
      timeout:
        type: number
        default: 150

jobs:
  quality:
    name: Quality Control
    uses: ./.github/workflows/nodejs_quality_control.yaml
    secrets: inherit

  config:
    name: Configure Artifacts
    runs-on: ubuntu-latest
    needs: quality

    steps:
    - name: Download Environment File
      uses: actions/download-artifact@v3
      with:
        name: environment-file

    - name: Convert Environment File to YAML
      run: sed -i -E 's/=(.+[^=])/:\1/g' .env

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: .env

  deploy:
    name: Cloud Run Deploy
    uses: ./.github/workflows/gcp_cloud_run_deploy.yaml
    secrets: inherit
    needs: config

    with:
      ingress: ${{ inputs.ingress }}
      execution-environment: ${{ inputs.execution-environment }}
      cpu: ${{ inputs.cpu }}
      max-instances: ${{ inputs.max-instances }}
      concurrency: ${{ inputs.concurrency }}
      timeout: ${{ inputs.timeout }}
      deploy-args: '--env-vars-file .env'
