name: Node.js Quality Control

on:
  workflow_call:

env:
  NPM_TOKEN: ${{ secrets.GLB_NPM_TOKEN }}

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Download Environment File
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: environment-file

      - name: Install Dependencies
        run: |
          npm i -g pnpm
          pnpm i --frozen-lockfile
      - name: Run Unit Test
        run: pnpm test

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: |
            coverage
            test-report.xml
  build:
    name: Build Dry Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm i -g pnpm
          pnpm i --frozen-lockfile
      - name: Run Build Dry Run
        run: pnpm build

  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm i -g pnpm
          pnpm i --frozen-lockfile
      - name: Run Lint Check
        run: pnpm lint