name: NPM Publish Package

on:
  workflow_call:
    inputs:
      ref:
        description: 'Reference to shared workflows'
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  quality:
    name: Quality Control
    uses: ./.github/workflows/nodejs_quality_control.yaml
    secrets: inherit

  publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          repository: cnpja/workflows
          path: workflows
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Publish Package to NPM
        env:
          HUSKY: 0
        run: |
          npm i -g pnpm @semantic-release/changelog @semantic-release/git semantic-release
          pnpm i --frozen-lockfile --ignore-scripts
          pnpm build
          semantic-release
