name: NPM Publish Package

on:
  workflow_call:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.GLB_NPM_TOKEN }}

jobs:
  quality:
    name: Quality Control
    uses: ./.github/workflows/nodejs_quality_control.yaml
    secrets: inherit

  publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          npm i -g pnpm@7.25.0 semantic-release@19.0.5
          pnpm i --frozen-lockfile --ignore-scripts

      - name: Build Distributable
        run: pnpm build

      - name: Publish Package
        env:
          HUSKY: 0
        run: semantic-release
